#ifndef REPLY_HPP
#define REPLY_HPP

//PASS
#define ERR_NEEDMOREPARAMS 461
#define ERR_ALREADYREGISTRED 462

#define ERR_NEEDMOREPARAMS_STR ":Not enough parameters"
#define ERR_ALREADYREGISTRED_STR ":You may not reregister"
//PASS: ERR_NEEDMOREPARAMS, ERR_ALREADYREGISTRED

//NICK
#define ERR_NONICKNAMEGIVEN 431
#define ERR_ERRONEUSNICKNAME 432
#define ERR_NICKNAMEINUSE 433
#define ERR_NICKCOLLISION 436

#define ERR_NONICKNAMEGIVEN_STR ":No nickname given"
#define ERR_ERRONEUSNICKNAME_STR ":Erroneus nickname"
#define ERR_NICKNAMEINUSE_STR ":Nickname is already in use"
#define ERR_NICKCOLLISION_STR ":Nickname collision KILL"
//NICK: ERR_NONICKNAMEGIVEN, ERR_ERRONEUSNICKNAME, ERR_NICKNAMEINUSE, ERR_NICKCOLLISION

//USER
//USER: ERR_NEEDMOREPARAMS, ERR_ALREADYREGISTRED

//OPER
#define RPL_YOUREOPER 381

#define ERR_PASSWDMISMATCH 464
#define ERR_NOOPERHOST 491

#define ERR_PASSWDMISMATCH_STR ":Password incorrect"
#define ERR_NOOPERHOST_STR ":No O-lines for your host"
//OPER: ERR_NEEDMOREPARAMS, RPL_YOUREOPER, ERR_NOOPERHOST, ERR_PASSWDMISMATCH

//JOIN
#define RPL_TOPIC 332

#define ERR_CHANNELISFULL 471
#define ERR_BANNEDFROMCHAN 474
#define ERR_INVITEONLYCHAN 473
#define ERR_BADCHANMASK 476
#define ERR_NOSUCHCHANNEL 403
#define ERR_TOOMANYCHANNELS 405

#define ERR_CHANNELISFULL_STR ":Cannot join channel (+l)"
#define ERR_BANNEDFROMCHAN_STR ":Cannot join channel (+b)"
#define ERR_INVITEONLYCHAN_STR ":Cannot join channel (+i)"
#define ERR_NOSUCHCHANNEL_STR ":No such channel"
#define ERR_TOOMANYCHANNELS_STR ":You have joined too many channels"
//JOIN: ERR_NEEDMOREPARAMS, ERR_BANNEDFROMCHAN, ERR_INVITEONLYCHAN, ERR_BADCHANNELKEY, ERR_CHANNELISFULL, ERR_BADCHANMASK, ERR_NOSUCHCHANNEL, ERR_TOOMANYCHANNELS, RPL_TOPIC

//PART
#define ERR_NOTONCHANNEL 442
//PART: ERR_NEEDMOREPARAMS, ERR_NOSUCHCHANNEL, ERR_NOTONCHANNEL

//MODE
#define RPL_CHANNELMODEIS 324
#define RPL_BANLIST 367
#define RPL_ENDOFBANLIST 368
#define RPL_UMODEIS 221

#define ERR_CHANOPRIVSNEEDED 482
#define ERR_NOSUCHNICK 401
#define ERR_KEYSET 467
#define ERR_UNKNOWNMODE 472
#define ERR_USERSDONTMATCH 502
#define ERR_UMODEUNKNOWNFLAG 501
//MODE: ERR_NEEDMOREPARAMS, RPL_CHANNELMODEIS, ERR_CHANOPRIVSNEEDED, ERR_NOSUCHNICK, ERR_NOTONCHANNEL, ERR_KEYSET, RPL_BANLIST, RPL_ENDOFBANLIST, ERR_UNKNOWNMODE, ERR_NOSUCHCHANNEL, ERR_USERSDONTMATCH, RPL_UMODEIS, ERR_UMODEUNKNOWNFLAG

//TOPIC
#define RPL_NOTOPIC 331
//TOPIC: RPL_NOTOPIC, RPL_TOPIC, ERR_NEEDMOREPARAMS, ERR_NOTONCHANNEL ,ERR_CHANOPRIVSNEEDED

//NAMES
#define RPL_NAMREPLY 353
#define RPL_ENDOFNAMES 366
//NAMES: RPL_NAMREPLY, RPL_ENDOFNAMES

//LIST
#define RPL_LISTSTART 321
#define RPL_LIST 322
#define RPL_LISTEND 323

#define ERR_NOSUCHSERVER 402
//LIST: ERR_NOSUCHSERVER, RPL_LISTSTART, RPL_LIST, RPL_LISTEND

//INVITE
#define RPL_AWAY 301
#define RPL_INVITING 341

#define ERR_USERONCHANNEL 443
//INVITE: ERR_NEEDMOREPARAMS, ERR_NOSUCHNICK, ERR_NOTONCHANNEL, ERR_USERONCHANNEL, ERR_CHANOPRIVSNEEDED, RPL_INVITING, RPL_AWAY

//KICK
//KICK: ERR_NEEDMOREPARAMS, ERR_NOSUCHCHANNEL, ERR_BADCHANMASK, ERR_CHANOPRIVSNEEDED, ERR_NOTONCHANNEL

//SERVER
#define RPL_VERSION 351
//SERVER: ERR_NOSUCHSERVER, RPL_VERSION

//LINKS
#define RPL_LINKS 364
#define RPL_ENDOFLINKS 365
//LINKS: ERR_NOSUCHSERVER, RPL_LINKS, RPL_ENDOFLINKS

//TIME
#define RPL_TIME 391
//TIME: ERR_NOSUCHSERVER, RPL_TIME

//ADMIN
#define RPL_ADMINME 256
#define RPL_ADMINLOC1 257
#define RPL_ADMINLOC2 258
#define RPL_ADMINEMAIL 259
//ADMIN: ERR_NOSUCHSERVER, RPL_ADMINME, RPL_ADMINLOC1, RPL_ADMINLOC2, RPL_ADMINEMAIL


//INFO
#define RPL_INFO 371
#define RPL_ENDOFINFO 374
//INFO: ERR_NOSUCHSERVER, RPL_INFO, RPL_ENDOFINFO

//PRIVMSG
#define ERR_NORECIPIENT 411
#define ERR_NOTEXTTOSEND 412
#define ERR_CANNOTSENDTOCHAN 404
#define ERR_NOTOPLEVEL 413
#define ERR_WILDTOPLEVEL 414
#define ERR_TOOMANYTARGETS 407
//PRIVMSG: ERR_NORECIPIENT, ERR_NOTEXTTOSEND, ERR_CANNOTSENDTOCHAN, ERR_NOTOPLEVEL, ERR_WILDTOPLEVEL, ERR_TOOMANYTARGETS, ERR_NOSUCHNICK, RPL_AWAY

//WHO
#define RPL_WHOREPLY 352
#define RPL_ENDOFWHO 315
// WHO: ERR_NOSUCHSERVER, RPL_WHOREPLY, RPL_ENDOFWHO

// KILL
#define ERR_NOPRIVILEGES 481
#define ERR_CANTKILLSERVER 483
// KILL: ERR_NOPRIVILEGES, ERR_NEEDMOREPARAMS, ERR_NOSUCHNICK, ERR_CANTKILLSERVER


// PING
#define ERR_NOORIGIN 409
// PING: ERR_NOORIGIN, ERR_NOSUCHSERVER

// PONG
// PONG: ERR_NOORIGIN, ERR_NOSUCHSERVER

#endif