#ifndef REPLY_HPP
#define REPLY_HPP

//USER, OPER
#define ERR_NEEDMOREPARAMS 461
#define ERR_ALREADYREGISTRED 462
#define ERR_PASSWDMISMATCH 464


//NICK
#define ERR_NONICKNAMEGIVEN 431
#define ERR_ERRONEUSNICKNAME 432
#define ERR_NICKNAMEINUSE 433
#define ERR_NICKCOLLISION 436

#define ERR_NONICKNAMEGIVEN_STR ":No nickname given"
#define ERR_ERRONEUSNICKNAME_STR ":Erroneus nickname"
#define ERR_NICKNAMEINUSE_STR ":Nickname is already in use"
#define ERR_NICKCOLLISION_STR ":Nickname collision KILL"

//OPER
#define RPL_YOUREOPER 381
#define ERR_NOOPERHOST 491

//JOIN
#define RPL_TOPIC 332

#define ERR_BANNEDFROMCHAN 474
#define ERR_INVITEONLYCHAN 473
#define ERR_CHANNELISFULL 471
#define ERR_BADCHANMASK 476
#define ERR_NOSUCHCHANNEL 403
#define ERR_TOOMANYCHANNELS 405

//PART
#define ERR_NOTONCHANNEL 442

//MODE
#define RPL_CHANNELMODEIS 324
#define RPL_BANLIST 367
#define RPL_ENDOFBANLIST 368
#define RPL_UMODEIS 221

#define ERR_CHANOPRIVSNEEDED 482
#define ERR_NOSUCHNICK 401
#define ERR_KEYSET 467
#define ERR_UNKNOWNMODE 472
#define ERR_USERSDONTMATCH 502
#define ERR_UMODEUNKNOWNFLAG 501

//TOPIC
#define RPL_NOTOPIC 331
#define RPL_TOPIC 332

//TOPIC: RPL_NOTOPIC, RPL_TOPIC, ERR_NEEDMOREPARAMS, ERR_NOTONCHANNEL ,ERR_CHANOPRIVSNEEDED

//NAMES
#define RPL_NAMREPLY 353
#define RPL_ENDOFNAMES 366

//NAMES: RPL_NAMREPLY, RPL_ENDOFNAMES

//LIST
#define RPL_LISTSTART 321
#define RPL_LIST 322
#define RPL_LISTEND 323

#define ERR_NOSUCHSERVER 402
//LIST: ERR_NOSUCHSERVER, RPL_LISTSTART, RPL_LIST, RPL_LISTEND

//INVITE
#define RPL_AWAY 301
#define RPL_INVITING 341

#define ERR_USERONCHANNEL 443
//INVITE: ERR_NEEDMOREPARAMS, ERR_NOSUCHNICK, ERR_NOTONCHANNEL, ERR_USERONCHANNEL, ERR_CHANOPRIVSNEEDED, RPL_INVITING, RPL_AWAY

//KICK
//KICK: ERR_NEEDMOREPARAMS, ERR_NOSUCHCHANNEL, ERR_BADCHANMASK, ERR_CHANOPRIVSNEEDED, ERR_NOTONCHANNEL

//SERVER
#define RPL_VERSION 351
//SERVER: ERR_NOSUCHSERVER, RPL_VERSION

//LINKS
#define RPL_LINKS 364
#define RPL_ENDOFLINKS 365
//LINKS: ERR_NOSUCHSERVER, RPL_LINKS, RPL_ENDOFLINKS

//TIME
#define RPL_TIME 391
//TIME: ERR_NOSUCHSERVER, RPL_TIME

//ADMIN
#define RPL_ADMINME 256
#define RPL_ADMINLOC1 257
#define RPL_ADMINLOC2 258
#define RPL_ADMINEMAIL 259
//ADMIN: ERR_NOSUCHSERVER, RPL_ADMINME, RPL_ADMINLOC1, RPL_ADMINLOC2, RPL_ADMINEMAIL


//INFO
#define RPL_INFO 371
#define RPL_ENDOFINFO 374
//INFO: ERR_NOSUCHSERVER, RPL_INFO, RPL_ENDOFINFO


#endif